# Generated by Django 3.1.1 on 2020-09-22 00:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(blank=True, null=True, verbose_name='Data da agenda')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
                'ordering': ('dia',),
            },
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Especialidade Medica',
                'verbose_name_plural': 'Especialidades Medicas',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^[0-9]+$')], verbose_name='CRM')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=120, null=True, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, help_text='DDD+Número Ex.: 83987999999', max_length=12, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{10,12}$')], verbose_name='Telefone')),
                ('especialidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.especialidade', verbose_name='Especialidade')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(verbose_name='Horários disponíveis')),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.agenda', verbose_name='Agenda')),
            ],
            options={
                'verbose_name': 'Hora',
                'verbose_name_plural': 'Horas',
                'ordering': ('hora',),
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('horario', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hora')),
                ('data_agendamento', models.DateField(auto_now_add=True, verbose_name='Data do agendamento')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medico', verbose_name='Médico')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ('dia', 'horario'),
            },
        ),
        migrations.AddField(
            model_name='agenda',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medico', verbose_name='Médico'),
        ),
    ]
