# Generated by Django 3.1.1 on 2020-09-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='vago',
            field=models.BooleanField(default=True),
        ),
    ]
