# Generated by Django 3.1.1 on 2020-09-22 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_consulta_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ('horario',), 'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='medico',
        ),
        migrations.AlterField(
            model_name='consulta',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.horario', verbose_name='Horario'),
        ),
    ]
