# Generated by Django 3.1.1 on 2020-09-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200922_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ('horario__agenda__dia', 'horario__hora'), 'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora',
            field=models.TimeField(verbose_name='Horários'),
        ),
    ]
